version: "3.9"

services:
  backend-db:
    container_name: backend-dbContext
    image: postgres:alpine
    volumes:
      - dbContext-data:/var/lib/postgresql/data
    networks:
      - backend-net
    restart: unless-stopped
    ports:
      - "5432:5432"
    env_file:
      - ../configs/dotenv/postgres.env

  backend-app:
    container_name: backend-app
    depends_on:
      - backend-db
    build:
      context: ../
      dockerfile: build/package/Dockerfile
    networks:
      - backend-net
    ports:
      - "8000:8000"

volumes:
  db-data:
    driver: local

networks:
  backend-net:
    driver: bridge